INSERT INTO Productos (nombre, precio, categoria, descripcion) VALUES
('Camiseta River', 40000, 'camiseta', 'Camiseta de jugadores de voley de river '),
('Camiseta Boca', 40000, 'camiseta', 'Camiseta de jugadores de voley de boca '),
('Camiseta Brasil Darlan', 60000, 'camiseta', 'Camiseta de Darlan en la seleccion de brasil'),
('Camiseta Ferro', 40000, 'camiseta', 'Camiseta de jugadores de voley de Ferro'),
('Camiseta Japon Nishida', 60000, 'camiseta', 'Camiseta de Nishida en la seleccion japonesa 2018'),
('Camiseta las pumas', 60000, 'camiseta', 'Camiseta de la seleccion argentina de las pumas'),
('Camiseta Argentina clasica', 60000, 'camiseta', 'Camiseta de la seleccion argentina de voley'),
('Camiseta Argentina alternativa', 60000, 'camiseta', 'Camiseta de la seleccion argentina de voley alternativa'),
('Asics gel rebound', 90000, 'zapatilla', 'Zapatillas Asics gel rebound'),
('Asics mujer gel comulus 24', 107000, 'zapatilla', 'Zapatillas Asics gel comulus24 para mujer'),
('Mizuno W lightning Z3', 370000, 'zapatilla', 'Exclusivas zapatillas Mizuno W lightning Z3 zebra'),
('Mizuno wave mirai 6', 180000, 'zapatilla', 'Zapatillas mizuno wave M6'),
('Nike kyrie 7', 210000, 'zapatilla', 'Las increibles nike kyrie 7, te las vas a perder?'),
('Nike kyrie 8', 470000, 'zapatilla', 'Exclusivas zapatillas nike kyrie 8'),
('Nike precision 6', 98000, 'zapatilla', 'Presicon 6 un modelo que todo deportista deberia tener'),
('Nike precision 7', 150000, 'zapatilla', 'Confortables Nike precision 7, resbalarse nunca fue una opcion');