INSERT INTO Products (name, price, category, description, active) VALUES
('Bota FINDERS modelo ACCURATE indoor', 219999, 'zapatilla', 'Bota FINDERS modelo ACCURATE para indoor', True),
('Bota HEAD TOKIO LOW', 89999, 'zapatilla', 'Bota HEAD TOKIO LOW para indoor', True),
('Bota PEAK Power P-Motivo (Unisex)', 97990, 'zapatilla', 'Bota PEAK Power P-Motivo para unisex', True),
('Botas NEW BALANCE TWO V2 Multicolor', 110000, 'zapatilla', 'Botas NEW BALANCE TWO W2 Multicolor', True),
('Buzo Canguro LeCoq Seleccion Argentina de Voley (Unisex)', 60000, 'indumentaria', 'Buzo canguro LeCoq oficial de la Selección Argentina de Voley', True),
('Calza Corta Lisa Thorium', 18999, 'indumentaria', 'Calza corta lisa marca Thorium', True),
('Camiseta De Cecco MODENA temporada 2024-25 (amarilla)', 29999, 'indumentaria', 'Camiseta De Cecco MODENA temporada 2024-25 color amarilla', True),
('Camiseta De Cecco MODENA temporada 2024-25', 29999, 'indumentaria', 'Camiseta De Cecco MODENA temporada 2024-25', True),
('Camiseta Ishikawa Seleccion de Japon VNL 2024 y JJOO de Paris', 29999, 'indumentaria', 'Camiseta Ishikawa Selección Japón VNL 2024 y JJOO de París', True),
('Camiseta Ishikawa SIR PERUGIA temporada 2024-25', 29999, 'indumentaria', 'Camiseta Ishikawa SIR PERUGIA temporada 2024-25', True),
('Camiseta Lecoq Oficial Seleccion Argentina de Voley Masculina (Albiceleste)', 82000, 'indumentaria', 'Camiseta Lecoq oficial Selección Argentina de Voley Masculina albiceleste', True),
('Camiseta Lecoq Oficial Seleccion Argentina de Voley Masculina (negra)', 82000, 'indumentaria', 'Camiseta Lecoq oficial Selección Argentina de Voley Masculina color negro', True),
('Camiseta Lecoq Oficial Seleccion Argentina de Voley Panteras (negra)', 82000, 'indumentaria', 'Camiseta Lecoq oficial Selección Argentina de Voley Panteras color negro sin mangas', True),
('Camiseta Lecoq Oficial Seleccion Argentina de Voley Panteras (Albiceleste)', 82000, 'indumentaria', 'Camiseta Lecoq oficial Selección Argentina de Voley Panteras albiceleste sin mangas', True),
('Camiseta Loser SIR PERUGIA temporada 2024-25 (negro)', 29999, 'indumentaria', 'Camiseta Loser SIR PERUGIA temporada 2024-25 color negro', True),
('Camiseta Loser SIR PERUGIA temporada 2024-25', 29999, 'indumentaria', 'Camiseta Loser SIR PERUGIA temporada 2024-25', True),
('Camiseta Nishida Seleccion de Japon VNL 2024 y JJOO de Paris', 29999, 'indumentaria', 'Camiseta Nishida Selección Japón VNL 2024 y JJOO de París', True),
('Camiseta Seleccion USA Voley Unisex', 49999, 'indumentaria', 'Camiseta oficial Selección USA Voley unisex', True),
('Camiseta Termica Thorium Unisex (Azul)', 27990, 'indumentaria', 'Camiseta térmica Thorium unisex color azul', True),
('Camiseta Ran Seleccion de Japon VNL 2024 y JJOO de Paris', 29999, 'indumentaria', 'Camiseta San Renaud Selección Japón VNL 2024 y JJOO de París', True),
('Campera con capucha Seleccion Japonesa de voley (EDICION LIMITADA)', 95000, 'indumentaria', 'Campera con capucha Selección Japonesa de Voley edición limitada', True),
('Short Beach Voley y entrenamiento indoor LeCoq seleccion Argentina de Voley 2024', 24599, 'indumentaria', 'Short Brack Voley y entrenamiento LeCoq Selección Argentina 2024', True),
('Short de Lycra deportivo VYOS', 18499, 'indumentaria', 'Short de lycra deportivo VYOS', True),
('Short Deportivo Thorium', 23000, 'indumentaria', 'Short deportivo Thorium', True),
('Top Deportivo Thorium', 14999, 'indumentaria', 'Top deportivo Thorium', True),
('Zapatillas Asics Sky Elite PARIS 2024 FF3 TM', 299999, 'zapatilla', 'Zapatillas Asics Sky Elite PARIS 2024 FF3 TM', True),
('Zapatillas AVIA SHUTTLE MID', 124999, 'zapatilla', 'Zapatillas AVIA SHUTTLE MID', True),
('Zapatillas Mizuno Wave Lightning Z3 EDICION LIMITADA', 189999, 'zapatilla', 'Zapatillas Mizuno Wave Lightning Z3 edición limitada', True),
('Zapatillas NIKE HYPERHACE 3', 249999, 'zapatilla', 'Zapatillas NIKE HYPERACE 3', True),
('Zapatillas NIKE HYPERSET 2', 262999, 'zapatilla', 'Zapatillas NIKE HYPERSET 2', True),
('Zapatillas NIKE HYPERSPEED COURT', 189999, 'zapatilla', 'Zapatillas NIKE HYPERSPPED COURT', True),
('Zapatillas Nike Precision 7', 139999, 'zapatilla', 'Zapatillas Nike Precision 7', True),
('Zapatillas Olympikus Qu4dra BR1', 199990, 'zapatilla', 'Las Olympicus Qu4dra BR1 en color negro', True),
('Zapatillas PEAK Arwind Santos L.E SonicBoom (Unisex) (Rose-Pink)', 138999, 'zapatilla', 'Zapatillas PEAK Arwind Santos unisex color Rose-Pink', True),
('Zapatillas PEAK DEFENDER Unisex con Tecnologia Taichi', 129999, 'zapatilla', 'Zapatillas PEAK Arwind SonicBoom con Tecnología Taichi', True),
('Zapatillas PEAK TAICHI FLASH SAKURA (Women) Edicion Limitada', 149999, 'zapatilla', 'Zapatillas PEAK TAICHI FLASH SAKURA para mujer edición limitada', True);