DROP TABLE IF EXISTS Products;

CREATE TABLE IF NOT EXISTS Products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  price REAL,
  category TEXT,
  description TEXT,
  active BOOLEAN
  );

DROP TABLE IF EXISTS Users;

CREATE TABLE IF NOT EXISTS Users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  password TEXT
);

DROP TABLE IF EXISTS Sales;

CREATE TABLE IF NOT EXISTS Sales (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,
    client_name TEXT NOT NULL,
    total INTEGER
);

DROP TABLE IF EXISTS SaleDetails;

CREATE TABLE IF NOT EXISTS SaleDetails (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_sale INTEGER NOT NULL,
    id_product INTEGER NOT NULL,
    count INTEGER NOT NULL,
    FOREIGN KEY (id_sale) REFERENCES Sales(id),
    FOREIGN KEY (id_product) REFERENCES Products(id)
);


-- sqlite